# Generated by Django 3.0.3 on 2020-02-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('ride_created_by', models.CharField(max_length=40)),
                ('source', models.IntegerField()),
                ('destination', models.IntegerField()),
                ('timestamp', models.CharField(default='', max_length=19)),
                ('riders_list', models.TextField(default='')),
            ],
        ),
    ]
